name: Generate Snake

on:
  # تشغيل كل 6 ساعات تلقائياً
  schedule:
    - cron: "0 */6 * * *"
  # يسمح لك بتشغيلها يدوياً
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          # اسم المستخدم الخاص بك
          github_user_name: seif-elmuselmani
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
